name: Search for OLX postings

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - name: Cache listings
        uses: actions/cache@v3
        with:
          path: ./listings.json
          key: item-listings-v2
      - name: Build scraper
        shell: bash
        run: >
          go build
      - name: Scrape data
        shell: bash
        run: >
          ./olxscraper -client ${{ secrets.CLIENT_ID }} ${{ secrets.KEYWORDS }}
